# Generated by Django 3.2 on 2021-08-11 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2021, 8, 11), verbose_name='Jaxon primyerasi'),
        ),
    ]
