# Generated by Django 3.2.4 on 2021-08-31 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'reyting yulduzcha', 'verbose_name_plural': 'reyting yulduzchalari'},
        ),
        migrations.AddField(
            model_name='actor',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='actor',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='davlat'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='davlat'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='spogan'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_uz',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='spogan'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izox'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlavha'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2021, 8, 31), verbose_name='Jaxon primyerasi'),
        ),
    ]
